### ISSUE TITLE
Remove comments from .eslintrc.json

### ISSUE THREAD

**Issue by perceptron8** [domenic/sinon-chai#103]
`//…` and `/*…*/` are not allowed in JSON. Please, remove them if you can.

Source:
http://www.json.org/
https://www.ietf.org/rfc/rfc4627.txt
https://www.ietf.org/rfc/rfc7159.txt

**Comment by domenic** [comment]
eslintrc is not JSON. Source: eslint.org.

**Comment by perceptron8** [comment]
You mean http://eslint.org/docs/user-guide/configuring#configuration-file-formats? As far as i understand, `eslintrc.json` is JSON.

I didn't know, however, that "ESLint’s JSON" ≠ "JSON". That's a pity. Eclipse gives me a few additional errors, but I can live with that.

Thanks for quick response!
