### ISSUE TITLE
calledWithExactly AssertionError has un-interpolated placeholder for zero args

### ISSUE THREAD

**Issue by jasonkarns** [domenic/sinon-chai#105]
When doing a calledWithExactly assertion, asserting _zero_ args, the failure message has a stray `%D` in the message.

```js
var spy = sinon.spy();

function foo(f) {
  f("invalid invocation");
}

foo(spy);

expect(spy).calledWithExactly();
```

The expected AssertionError is:
`AssertionError: expected spy to have been called with exact arguments`

but what's actually thrown is:
`AssertionError: expected spy to have been called with exact arguments %D`

Note: The vanilla sinon assertion `sinon.assert.calledWithExactly(spy)` throws: `AssertError: expected spy to be called with exact arguments`

**Comment by domenic** [comment]
What version of Sinon are you using? Have you tried the latest one?

**Comment by jasonkarns** [comment]
i threw this together on requirebin using latest, but chai wouldn't browserify correctly. then I verified my example above locally in node, but with our app's current version specs...

I'll update to latest and re-test when I get back this evening (running out the door right now...)

**Comment by jasonkarns** [comment]
Doesn't manifest with sinon@2. Too bad bumping major versions in our app will be a PITA :(
