### ISSUE TITLE
Issue with .called

### ISSUE THREAD

**Issue by westy92** [domenic/sinon-chai#106]
Node.js: 6.11.1 and 7.10.1 (latest) (works as expected on 8!)
chai: 4.1.0 (latest)
sinon: 2.4.1 (latest)
sinon-chai: 2.12.0 (latest)

Relevant lines (from https://github.com/westy92/html-pdf-chrome/blob/greenkeeper/initial/test/index.ts#L72):
```js
const launchStub = sinon.stub(chromeLauncher, 'launch');
expect(launchStub).to.not.have.been.called;
```

Error (from https://travis-ci.org/westy92/html-pdf-chrome/jobs/254586203#L640):
```
Error: Invalid Chai property: called. Did you mean "sealed"?
      at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:63:17)
      at Object.<anonymous> (lib/test/index.js:73:52)
      at Generator.next (<anonymous>)
      at fulfilled (lib/test/index.js:4:58)
```

Here's the relevant build information.  It passes on Node 8 Linux and Mac but fails on 6/7 on both platforms.
https://travis-ci.org/westy92/html-pdf-chrome/builds/254586197

PR: https://github.com/westy92/html-pdf-chrome/pull/18

**Comment by domenic** [comment]
Can you provide a self-contained example (maybe 5-10 lines, including requires) I can run to reproduce this problem, instead of something involving HTML, PDFs, and Chrome?

**Comment by westy92** [comment]
Interesting.  Turns out I could get by without `chai.use(require('sinon-chai'));` in former versions and still on Node.js 8, but no longer on 6 or 7.  Adding that seems to have fixed this particular error.
