### ISSUE TITLE
Support sinon 3+

### ISSUE THREAD

**Issue by AviVahl** [domenic/sinon-chai#107]
sinon 3.0.0 was just released.
This package currently specifies:
```
  "peerDependencies": {
    "sinon": "^1.4.0 || ^2.1.0"
    ...
  }
```

So a warning is printed (in npm/yarn) when trying to use the two together.
I guess this requires verifying that everything still works, and then updating the `peerDependencies`.

**Comment by domenic** [comment]
Fixed by https://github.com/domenic/sinon-chai/pull/108.
