### ISSUE TITLE
.calledWith doesn't handle deep comparison of some nested arrays correctly

### ISSUE THREAD

**Issue by ppg** [domenic/sinon-chai#109]
I made a gist to describe the failure:
https://gist.github.com/ppg/808697fdb740c284aaafc681fbfd373f

It demonstrates that comparing the array in question succeeds with `.deep.equal` but not with `.deep.calledWith`.

**Comment by domenic** [comment]
`.deep.calledWith` is not a thing. This package just does what Sinon does, and Sinon doesn't have any `deep`.

**Comment by ppg** [comment]
Why would one not want `.deep.calledWith` to do `.deep.equal` on each argument provided? Clearly, it doesn't do that, hence this issue, but IMO that seems like exactly the expected behavior. It can be coined a feature instead of a bug, but I would think `sinon-chai` would conform to `sinon` _and_ `chai`, not pick arbitrary parts of the latter to support.

Also, is there any workaround? The only answer I've found is don't use `calledWith`.

**Comment by domenic** [comment]
In general, if you can figure out how to express your thing in Sinon, that knowledge will port over to Sinon-Chai. If you can't then Sinon-Chai will not help you.

**Comment by ppg** [comment]
Update the gist:
https://gist.github.com/ppg/808697fdb740c284aaafc681fbfd373f

Sinon only works to do the deep comparison correctly, sinon-chai doesn't port that knowledge over; seems like that is the criteria for it to be a bug?

**Comment by domenic** [comment]
That gist is extraordinarily large. Can you provide a single-line example of what you are currently doing in Sinon?
