### ISSUE TITLE
calledWithNew is not a function when used with rewire

### ISSUE THREAD

**Issue by Rhysjc** [domenic/sinon-chai#115]
My code:
```
const mySpy = sinon.spy();

rewiredModule.__set__('AClass', mySpy);

expect(mySpy).to.have.been.calledWithNew();
```

This happens will all of the `called` functions.

Note that if I comment out the line with `__set__` then I don't have a problem (though obviously the test fails).

**Comment by domenic** [comment]
Sounds like a problem with rewire?

**Comment by Rhysjc** [comment]
I've submitted the same issue there, but wasn't sure. Thought someone here may have had the same issue.
