### ISSUE TITLE
Support calledOnceWithExactly and calledOnceWith

### ISSUE THREAD

**Issue by andys8** [domenic/sinon-chai#116]
Sinon was released in version [4.3.0](https://github.com/sinonjs/sinon/releases/tag/v4.3.0) with `calledOnceWithExactly` and `calledOnceWith`. Would be great to support these methods which will lead to less boilerplate if testing a call happened once and with an exact argument.

https://github.com/sinonjs/sinon/pull/1686
https://github.com/sinonjs/sinon/issues/1247

**Comment by domenic** [comment]
A pull request adding these would be welcome. Check https://github.com/domenic/sinon-chai/commit/f0628a19d2a5848b535d469d62a2e6c598c82a20 for an example, although these days the tests are in normal JavaScript, thankfully.
