### ISSUE TITLE
Support calling calledOnce as a function

### ISSUE THREAD

**Issue by furstenheim** [domenic/sinon-chai#121]
Hi, this is more a feature request than a bug.
I see that the notation is expect(spy).calledOnce.

I understand that the error is thrown in the getter. However it feels a bit weird to have called executed in the getter. In fact even the IDE (webstorm) is marking the code as `expression is nor assignment or call`.

Would it be possible to allow calling it as a function? To make the intention more explicit?

**Comment by domenic** [comment]
No, I'm happy to have only one way to do things.
