### ISSUE TITLE
placeholders for comparing arguments

### ISSUE THREAD

**Issue by bahmutov** [domenic/sinon-chai#128]
I love `calledWith(a, b, c, ...)` semantics, and it would be very nice to have placeholders to only check arguments I am interested or can get to. For example, if we are only interested in 2nd and 3rd argument, but not the first one, we could do this

```js
expect(spy).to.have.been.calledWith(_, b, c)
```

for placeholder we could use something like `sinonChai ` itself

```
const _ = require('sinonChai')
expect(spy).to.have.been.calledWith(_, b, c)
```

What do you think?

**Comment by domenic** [comment]
This is already a feature of Sinon: http://sinonjs.org/releases/v6.1.3/matchers/ (`sinon.match.any`)
