### ISSUE TITLE
expect(STUB).to.not.have.been.called works but adding parens explodes

### ISSUE THREAD

**Issue by mandrewpowers** [domenic/sinon-chai#130]
In my test the following does what I'd expect:

```
expect(STUB).to.not.have.been.called;
```

but if I add parens to the end like I normally do I get an exception:

```
expect(STUB).to.not.have.been.called();
```

```
TypeError: expect(...).to.not.have.been.called is not a function
    at Context.it (test/integration/execute.test.js:23:53)
    at <anonymous>
```

_This only occurs when I add `.not.` to the chain._

**Comment by domenic** [comment]
Right, per the readme parens are not supported. Not sure why you started doing that. called is indeed not a function.

**Comment by mandrewpowers** [comment]
The docs do not explicitly state that parens will not work in this case. Also, why are they not supported? Ever other chai call works perfectly fine.

If I'm going to be stuck with linting errors because of that I'll probably just not use this at all I guess.
