### ISSUE TITLE
npm-check fails due to peer dependency of sinon < 7.0.0

### ISSUE THREAD

**Issue by stevegoossens** [domenic/sinon-chai#132]
Sinon 7.0.0 looks like it was released 3 days ago.

# sinon 6.3.5 installed

npm-check now fails, e.g.

```
sinon   😎  MAJOR UP  Major update available. https://sinonjs.org/
                     npm install --save-dev sinon@7.0.0 to go from 6.3.5 to 7.0.0

Use npm-check -u for interactive update.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

# sinon 7.0.0 installed

installing sinon@7.0.0 causes `npm test` failure due to:

```
npm WARN sinon-chai@3.2.0 requires a peer of sinon@>=4.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by pkuczynski** [comment]
This would be fixed by #131

**Comment by simondel** [comment]
I'm in contact with Domenic to transfer ownership to me so PR's can be merged and released.

**Comment by simondel** [comment]
I'll create a release today.

**Comment by simondel** [comment]
`sinon-chai@3.3.0` has been released 🎉
