### ISSUE TITLE
Typescript test: property 'calledOnce' does not exist on type 'Assertion'

### ISSUE THREAD

**Issue by crystalfp** [domenic/sinon-chai#145]
I'm not able to use stubs in mocha tests written with Typescript. Sinon-chai should solve this, but it seems not with typescript:

```
import {expect, use} from "chai";
import {stub} from "sinon";
require("mocha-sinon");
use(require("sinon-chai"));

describe("CommandLine", function() {
    before(function() {
	stub(console, "log");
    });
    it("Ask for help", function(done) {
	console.log("Help!");
	expect(console.log).calledOnce;
	done();
    });
});
```
(The strange import statements are the only one that works for me).

Running with: `mocha -r ts-node/register test.ts` gives:
```
TSError: Unable to compile TypeScript:
tests/CommandLine.test.ts(13,23): error TS2339: Property 'calledOnce' does not exist on type 'Assertion'.
```
How should I use your module with typescript tests?
Thanks!
mario

**Comment by crystalfp** [comment]
I have also installed the corresponding types `npm -D @types/sinon-chai` but no change. Or at least I don't know how to use them to solve my problem.

**Comment by crystalfp** [comment]
Apparently changing the `use` line to:
```
const uc = require("sinon-chai");
use(uc);
```
Solved the problem. I don't understand.
mario

**Comment by crystalfp** [comment]
It was a red herring. Reopening.
The test (see it at the end) runs without problems from `npm test` but inside VSCode `.calledOnce` is marked as: `Property 'calledOnce' does not exist on type 'Assertion'.ts(2339)` idem if I compile the tests using `tsc`.
Here is bug.test.ts:
```
import {expect, use} from "chai";
import {stub} from "sinon";  // eslint-disable-line import/named
require("mocha-sinon");
const uc = require("sinon-chai");
use(uc);

describe("Strange", function() {
    before(function() {
		stub(console, "info");
    });
    it("Calling console.info", function(done) {
		console.info("Help!");
		expect(console.info).calledOnce;
		done();
    });
});
```

**Comment by crystalfp** [comment]
Continuing my experiments I have found a setup that seems to work. You need to install `@types/sinon-chai`, then remove the following two lines from the test code above:
```
const uc = require("sinon-chai");
use(uc);
```
and change them to:
```
import sinonChai = require("sinon-chai");
use(sinonChai);
```
Now the only remaining problem is that don't know why it works. The use of `use` sound suspicious.
Hope someone can enlighten me.
Thanks!
mario

**Comment by RealZogger** [comment]
this is what works for me:

~~~
import * as chai from 'chai';
import * as sinonChai from 'sinon-chai';

chai.use(sinonChai);
~~~

**Comment by crystalfp** [comment]
Unfortunately eslint complains on the second import: `No exported names found in module 'sinon-chai'.` OK, this could be silenced.

But typescript gives an error on the `chai.use` line originating from the second import statement:
```
Argument of type '{ default: ChaiPlugin; }' is not assignable to parameter of type 'ChaiPlugin'.
  Type '{ default: ChaiPlugin; }' provides no match for the signature '(chai: ChaiStatic, utils: ChaiUtils): void'.
Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
```
So I suspect my `tsconfig.json` file is wrong somehow. Could you send me yours?
Thanks!
mario

**Comment by RealZogger** [comment]
After posting I had some doubts about my own code, because the `module.exports` for sinon-chai is a function. Although it happens to be working in the environment it's running on (vscode, TS 3.7.3) - I don't think that `import * as x` is actually valid when the exports is a function.

See https://blog.atomist.com/typescript-imports/ for some helpful information on the confusing import situation

I think you can use either
`import sinonChai = require("sinon-chai");`

or if you have `esModuleInterop` enabled this looks a bit nicer
`import sinonChai from "sinon-chai"`;

For reference, it's not my project, but here is the [tsconfig](https://github.com/RealZogger/vscode-perforce/blob/shelve-enhancements/tsconfig.json). They have unfortunately not enabled any linting, so the linter would probably have complained for my import.

I'll probably update my import to match your working example.

FWIW,
`const sinonChai = require('sinon-chai');` also works for me and runs succesfully, but does throw up an information message in vscode that `'require' call may be converted to an import.ts(80005)`

**Comment by crystalfp** [comment]
The strange thing is that I have both `"allowSyntheticDefaultImports": true` and `"esModuleInterop": true`, but `import sinonChai from "sinon-chai";` crashes during compilation because no default export found in imported module "sinon-chai".`
The only difference in tsconfig.json is the target that in my file is ES2018 and in your is ES6.
Anyway, it works, so I don't touch it.
And thanks for the links!

**Comment by RealZogger** [comment]
Just for the versions, what does the devDependencies look like in your package.json?

**Comment by crystalfp** [comment]
```
  "dependencies": {
    "body-parser": "^1.19.0",
    "commander": "^4.1.0",
    "compression": "^1.7.4",
    "cosmiconfig": "^6.0.0",
    "dagre": "^0.8.5",
    "elkjs": "^0.5.1",
    "express": "^4.17.1",
    "fs-extra": "^8.1.0",
    "glob": "^7.1.6",
    "http-status-codes": "^1.4.0",
    "iconv-lite": "^0.5.0",
    "js-yaml": "^3.13.1",
    "plugin-please": "^0.1.0",
    "serve-favicon": "^2.5.0",
    "spdy": "^4.0.1",
    "xml-js": "^1.6.11"
  },
  "devDependencies": {
    "@istanbuljs/nyc-config-typescript": "^1.0.1",
    "@types/chai": "^4.2.7",
    "@types/compression": "1.0.1",
    "@types/dagre": "^0.7.42",
    "@types/express": "^4.17.2",
    "@types/fs-extra": "^8.0.1",
    "@types/glob": "^7.1.1",
    "@types/jquery": "^3.3.31",
    "@types/js-yaml": "^3.12.1",
    "@types/knockout": "^3.4.66",
    "@types/marked": "^0.7.2",
    "@types/mocha": "^5.2.7",
    "@types/node": "^13.1.6",
    "@types/serve-favicon": "^2.5.0",
    "@types/sinon": "^7.5.1",
    "@types/sinon-chai": "^3.2.3",
    "@types/spdy": "^3.4.4",
    "@typescript-eslint/eslint-plugin": "^2.15.0",
    "@typescript-eslint/parser": "^2.15.0",
    "acorn": "^7.1.0",
    "chai": "^4.2.0",
    "eslint": "^6.8.0",
    "eslint-import-resolver-typescript": "^2.0.0",
    "eslint-plugin-chai-friendly": "^0.5.0",
    "eslint-plugin-const-case": "^1.2.2",
    "eslint-plugin-dollar-sign": "^1.0.2",
    "eslint-plugin-eslint-comments": "^3.1.2",
    "eslint-plugin-import": "^2.20.0",
    "eslint-plugin-jquery": "^1.5.1",
    "eslint-plugin-mocha": "^6.2.2",
    "eslint-plugin-no-useless-assign": "^1.0.3",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-optimize-regex": "^1.1.7",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-requirejs": "^4.0.0",
    "eslint-plugin-security": "^1.4.0",
    "eslint-plugin-unicorn": "^15.0.1",
    "mocha": "^7.0.0",
    "mocha-sinon": "^2.1.0",
    "nyc": "^15.0.0",
    "request": "^2.88.0",
    "sinon": "^8.0.4",
    "sinon-chai": "^3.4.0",
    "source-map-support": "^0.5.16",
    "ts-node": "^8.6.1",
    "typescript": "^3.7.4"
```

**Comment by RealZogger** [comment]
hmm, well I wondered if maybe it was something to do with using ts-node rather than tsc - made a very basic sample project

https://github.com/RealZogger/tsnode-test

based on your code with my import statement

It works fine when I run
`mocha -r ts-node/register src/mytest.ts`

**Comment by crystalfp** [comment]
Almost there!
Your test runs perfectly. Seems the problem is with eslint being overly zealous. It show the following two errors:
- `import {stub} from "sinon";` stub not found in 'sinon' eslint(import/named)
- `import * as sinonChai from "sinon-chai";`  No exported names found in module 'sinon-chai'. eslint(import/namespace)

Instead, the only error from ts (and it does not happen in mocha+ts-node, only in VSCode) is:
- `chai.use(sinonChai);` Argument of type '{ default: ChaiPlugin; }' is not assignable to parameter of type 'ChaiPlugin'. Type '{ default: ChaiPlugin; }' provides no match for the signature '(chai: ChaiStatic, utils: ChaiUtils): void'. Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.

So I will tune my eslint configuration. In the meantime, if there are no new ideas especially wrt VSCode and typescript, I propose to close this issue.
Thanks for your help!
mario

**Comment by crystalfp** [comment]
Adding
```
settings:
    import/ignore: [node_modules, tests]
```
silenced eslint, but the third error remains.

**Comment by RealZogger** [comment]
It's a mystery to me, as I am using vscode (1.41.1) and it doesn't show any problems for typescript on my repo. The import ... = require ... is probably a more correct option but I don't see why it would show up differently.

In the bottom right of the vscode window, which typescript version does it display when you open a typescript file? i.e. is it set to the project version or the vscode version?

**Comment by crystalfp** [comment]
I'm using the ts VSCode version that is 3.7.3. VSCode is 1.41.1 as yours.
My ts external version is 3.7.4 and that could explain the different behavior of the test inside/outside VSCode. If I remember how to use my version of ts inside VSCode, I will investigate this hypothesis.

**Comment by RealZogger** [comment]
You just click the version number to switch - but I started on 3.7.3 so don't think there is an issue there.

**Comment by crystalfp** [comment]
Tried. No changes with 3.7.4

**Comment by crystalfp** [comment]
Well, solved. I moved to jest and scrapped mocha+chai+sinon. Not nice to sinon-chai, but till now everything works as expected. 
Anyway, thanks for all the help!
