### ISSUE TITLE
sinon@9 peerDependency

### ISSUE THREAD

**Issue by ErikBean** [domenic/sinon-chai#147]
[sinon@9](https://github.com/sinonjs/sinon/blob/master/docs/changelog.md) got released today, and sinon-chai specifies a lower peerDependency:

npm WARN sinon-chai@3.4.0 requires a peer of sinon@>=4.0.0 <9.0.0
FYI @domenic @simondel

**Comment by simondel** [comment]
Fixed with 3.5.0 :)
