### ISSUE TITLE
Peer dep update for sinon 15

### ISSUE THREAD

**Issue by kf6kjg** [domenic/sinon-chai#158]
Same basic problem and solution as in previous update requests from others, this time for Sinon 15.

https://github.com/sinonjs/sinon/blob/main/CHANGES.md

**Comment by voxpelli** [comment]
Since version 3.7.0 there is no longer an upper version specified in the peer dependencies, so this should not be an issue anymore?

**Comment by kf6kjg** [comment]
Interesting. I came here because installation in new project threw errors about a version range mismatch when I had 15 installed, and worked fine when I downgraded to 14.

**Comment by kf6kjg** [comment]
You are correct. I misinterpreted the message to mean that both packages were causing the version mismatch when only one was, and that's not this package!

The message of importance:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: libraries@undefined
npm WARN Found: sinon@14.0.2
npm WARN node_modules/sinon
npm WARN   dev sinon@"15" from the root project
npm WARN   2 more (sinon-chai, sinon-test)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer sinon@"2.x - 14.x" from sinon-test@3.1.4
npm WARN node_modules/sinon-test
npm WARN   dev sinon-test@"3" from the root project
```

Closing this as there's no problem here.
