### ISSUE TITLE
jshint complains about some sinon-chai matchers

### ISSUE THREAD

**Issue by kikito** [domenic/sinon-chai#20]
jshint complains about sinon-chai's "parent-less" methods. For example, this line:

```
expect(load).to.have.been.calledOnce;
```

Gave me this message:

```
Linting test/test.js...ERROR
[L26:C37] Expected an assignment or function call and instead saw an expression.
      expect(load).to.have.been.calledOnce;
```

Would it be possible to have calledOnce & CO return a function instead of an object, so I can add parents at the end?

```
expect(load).to.have.been.calledOnce();
```

This would appease the hinter beast (it was also kindof what I expected when I started using this lib)

Thanks!

**Comment by daanvanhulst** [comment]
For eslint one would use: `/* eslint no-unused-expressions: 0 */`
