### ISSUE TITLE
Support for Chai 2.0

### ISSUE THREAD

**Issue by demisx** [domenic/sinon-chai#58]
Can this library also support chai 2.x?

**Comment by domenic** [comment]
Yeah I'll try to get around to it this weekend.

**Comment by demisx** [comment]
Thank you so much. 

**ATTENTION EVERYONE**: No +1's everyone or it will be delayed by a day per each occurrence!

**Comment by domenic** [comment]
2.7.0 released with Chai 2.x support.

**Comment by demisx** [comment]
:+1:
