### ISSUE TITLE
Possible to upgrade chai dependency?

### ISSUE THREAD

**Issue by bricejlin** [domenic/sinon-chai#60]
Is there an upgrade coming any time soon for chai 2+?

I'm running into peerDependency issues since another package (chai-as-promised) expects a higher chai version.

Thanks!

**Comment by domenic** [comment]
I don't understand. Sinon-Chai already supports Chai 2.x. Are you perhaps using an old version?

**Comment by bricejlin** [comment]
You are absolutely right, I forgot to update packages -_-
