### ISSUE TITLE
callHistory and exactCallHistory

### ISSUE THREAD

**Issue by charlierudolph** [domenic/sinon-chai#61]
These are two chai extensions I have been using and wonder if these could be added to the library.

```js
expect(@spy).to.have.callHistory(
  [call1Arg1, call1Arg2],
  [call2Arg1, call2Arg2]
)
```
instead of
```js
expect(@spy).to.have.been.calledTwice
expect(@spy).to.have.been.calledWith(call1Arg1, call1Arg2)
expect(@spy).to.have.been.calledWith(call2Arg1, call2Arg2)
```

it asserts the `callCount` is equal to the number of arguments provided and then checks the the spy was `calledWith` each of the arguments.

Happy to open a PR if this would be approved.

**Comment by domenic** [comment]
Are these in Simon?

**Comment by charlierudolph** [comment]
I don't understand your comment. I assume you mean "sinon" by the way. I'm proposing a new assertion that is just a combination of the existing assertions.

**Comment by domenic** [comment]
Sorry for the brevity and typo; I was on mobile.

Sinon–Chai's mission is to take all the asserters present in Sinon and make them available as a Chai plugin. If Sinon itself does not have an asserter, then it doesn't belong in Sinon–Chai.

That said, I'm happy to add a link to the readme to any npm package you publish which is a Chai plugin that also happens to work well with Sinon spies, even if not using the normal Sinon asserters API.

**Comment by hellboy81** [comment]
+1

We need also 2 versions: with `.calledAfter` and w/o

**Comment by domenic** [comment]
Since these don't appear in Sinon I'm closing this ticket until someone can show otherwise.
