### ISSUE TITLE
Avoid non-function chai matchers

### ISSUE THREAD

**Issue by jurko-gospodnetic** [domenic/sinon-chai#70]
I encountered an issue recently with `sinon-chai` caused by the design choice to make some of its `chai` matchers implemented as non--function properties.

If you perform an expectation like:

```
expect(spy).to.have.been.calledOnce;
```

that expectation will not fail if the test code fails to configure `chai` to support `sinon-chain` matchers, and will instead simply be quietly ignored.

On the other hand, if `sinon-chai` implemented such matchers using a function call syntax, as in:

```
expect(spy).to.have.been.calledOnce();
```

then forgetting to do `chai.use(require('sinon-chai'))` would not cause tests to be quietly ignored and would instead cause them to report an error complaining about `undefined` not being a callable.

**Comment by domenic** [comment]
I prefer the shorter syntax.
