### ISSUE TITLE
Support for Sinon 2.0

### ISSUE THREAD

**Issue by sjmulder** [domenic/sinon-chai#73]
As mentioned in [this comment by the maintainer](https://github.com/sinonjs/sinon/issues/830#issuecomment-159426720), Sinon 2.0 is due to come out any time now. The current version of sinon-chai requires Sinon 1.x.

**Comment by domenic** [comment]
Great. When it's actually out, we can do compatibility testing, update the code and raise the minimum version of necessary. Pull request welcome.

**Comment by sjmulder** [comment]
Sure. Maybe I'll have a go at testing against Sinon's current master branch to make the transition easy when the release comes around.

**Comment by pjanuario** [comment]
:+1:

**Comment by bcowgill** [comment]
+1 have to use sinon@2.0.0-pre to work with webpack and missing sinon-chai assertions

**Comment by bcowgill** [comment]
I have just tried sinon-chai 2.8.0 with  sinon@2.0.0-pre  and it just works. might be an easy update

**Comment by mgmcdermott** [comment]
I've forked this repository to support sinon 2.0 https://github.com/mgmcdermott/chai-sinon

**Comment by shikelong** [comment]
+1..

**Comment by CestDiego** [comment]
+1

**Comment by domenic** [comment]
As stated earlier in this thread, when Sinon 2.0 is actually released.

**Comment by eauc** [comment]
Hello,

Looks like sinon 2.0 was recently released.
I tried to run sinon-chai tests with sinon 2.0, and they worked, only but for a little error in expectation messages format...
I tracked down the error to a little bug in sinon, and made an issue & PR in sinon's github:
https://github.com/sinonjs/sinon/issues/1332
https://github.com/sinonjs/sinon/pull/1333
For me with this fix all the tests are green for sinon-chai with sinon 2.0

So I think sinon-chai can more or less support sinon 2.0 as soon as you want ;-)

thanks for your work !

**Comment by bricss** [comment]
Sinon 2.0 have landed :octocat:
https://github.com/sinonjs/sinon/releases/tag/v2.0.0

**Comment by domenic** [comment]
Great! I will work on this on the weekend.

**Comment by levithomason** [comment]
This might be of help:

http://sinonjs.org/releases/v2.0.0/migrating-to-2.0/
