### ISSUE TITLE
Allow making assertions on a sequence of calls

### ISSUE THREAD

**Issue by electricmonk** [domenic/sinon-chai#75]
I'd like to propose a feature to support the following:

```javascript
var visitor = sinon.spy();
[1,2].forEach(visitor);
expect(visitor).to.have.been.calledWith(1).then.calledWith(2).
```

If you're for it, I can try to contribute via PR

**Comment by domenic** [comment]
What Sinon assertion does this correspond to?

**Comment by electricmonk** [comment]
Sinon doesn't have this feature out of the box. Basically I'll be adding the `then` method, which would somehow iterate over `spy.getCalls`. Maybe each consecutive call to `then` will increment a flag, then I can do `getCall(utils.flag('sinon-call-depth').getAndIncrement())` to get the next call on each `then`.

**Comment by domenic** [comment]
Since Sinon doesn't have this feature, Sinon Chai should not. You should just use a series of assertions, instead of inventing a DSL.

**Comment by electricmonk** [comment]
The series of assertions would look like this:
```javascript
var visitor = sinon.spy();
[1,2].forEach(visitor);
expect(visitor.getCall(0).args[0]).to.equal(1));
expect(visitor.getCall(1).args[0]).to.equal(2));
```
which is much less readable and more error prone. The purpose of a matcher library like Chai is to abstract away such implementation details in favor of well-described expectations. Why should the fact that this feature doesn't correspond to a function of Sinon mean that Sinon-Chai shouldn't expose it?

**Comment by electricmonk** [comment]
For future reference, if anyone's interested, I ended up implementing this in a complementary plugin:
https://github.com/electricmonk/sinon-chai-in-order
