### ISSUE TITLE
Spy syntax is long-winded compared to RSpec

### ISSUE THREAD

**Issue by bsgreenb** [domenic/sinon-chai#79]
`expect(mySpy).to.have.been.calledWith("foo") //sinon-chai` 
compare to 
`expect(mySpy).to.have_received('foo') //rspec`

Is there some kind of syntactic sugar I can add to get the latter, more concise syntax?  Honestly I feel like this should be the default..

**Comment by thirdwaffle** [comment]
`have` and `been` are just [language chains](http://chaijs.com/api/bdd/#method_language-chains)  (unless they are overwritten by a plugin, but sinon-chai doesn't do that), so you don't have to use them. They only exist to make the statement read more naturally.

This:

    expect(mySpy).to.have.been.calledWith("foo")

can also be written as:

    expect(mySpy).to.be.calledWith("foo")

You can also eliminate the chains completely and just write:

    expect(mySpy).calledWith("foo")

**Comment by bsgreenb** [comment]
@thirdwaffle The rspec syntax is short, Rubyish in it's English-like readability, and uses the right tense.  The past tense fits in with the [4-phase test pattern](https://robots.thoughtbot.com/four-phase-test), because I make my assertions after I've executed my code.  So I'm talking about _what happened_ as opposed to what I expect to happen.  Here's where each of these falls short:

expect(mySpy).to.have.been.calledWith("foo") // Long winded
expect(mySpy).to.be.calledWith("foo") // Written in future-tense, in contrast to 4 phase pattern I use.
expect(mySpy).calledWith("foo") // not Rubyish, i.e. English sounding like `4.days.ago`

I imagine I could wrap your stuff in syntactic sugar though.  A lot of us stubborn rspec users would appreciate :)
