### ISSUE TITLE
ReferenceError: Can't find variable: chai

### ISSUE THREAD

**Issue by TeaBough** [domenic/sinon-chai#80]
I'm getting : `ReferenceError: Can't find variable: chai`

here is my loader file `/tests/test_index.js`: 

```
import 'babel-polyfill'
import sinon from 'sinon'

import chai from 'chai'
import sinonChai from 'sinon-chai'
import chaiAsPromised from 'chai-as-promised'
import chaiEnzyme from 'chai-enzyme'
import {mount, render, shallow} from 'enzyme'
chai.use(sinonChai)
chai.use(chaiAsPromised)
chai.use(chaiEnzyme())
...
```

Here is a part of my `package.json`

```
...
    "chai": "^3.4.1",
    "chai-as-promised": "^5.1.0",
    "chai-enzyme": "^0.5.1",
    "sinon": "^1.17.3",
    "sinon-chai": "^2.8.0",
...
```

It works if a remove only `sinon-chai` ...

**Comment by domenic** [comment]
That syntax does not work in Node.js.

**Comment by TeaBough** [comment]
Which syntax should I use then ? I'm using the same syntax as in the starter kit : https://github.com/davezuko/react-redux-starter-kit/blob/master/tests/test-bundler.js

**Comment by domenic** [comment]
`require("chai")` etc.

**Comment by TeaBough** [comment]
same error with : 
```
require ('babel-polyfill')
var sinon = require('sinon')

var chai = require('chai')
var sinonChai = require('sinon-chai')
var chaiAsPromised = require('chai-as-promised')
var chaiEnzyme = require('chai-enzyme')
var {mount, render, shallow} = require('enzyme')

chai.use(sinonChai)
chai.use(chaiAsPromised)
chai.use(chaiEnzyme())

global.chai = chai
global.sinon = sinon
...
```

**Comment by domenic** [comment]
OK. Can you produce a small test file that I can run with `node file.js` and see the problem?

**Comment by carlkenne** [comment]
Sinon-chai is expecting a global require function, however, that might not always be present depending on how you import you modules.

If you are using webpack you can inject an empty require function into sinon-chai with the imports-loader to make it happier:
```
{
  test: require.resolve('sinon-chai'), //only do this for sinon-chai
  loader: 'imports-loader?require=>function(){}',
}
```

**Comment by domenic** [comment]
Closing due to lack of repro.
