### ISSUE TITLE
Support For Specific Arguments and Eql?

### ISSUE THREAD

**Issue by machineghost** [domenic/sinon-chai#81]
I just discovered sinon-chai a short while ago, and I love it.  However, I find myself still having to drop back to raw Sinon for one reason: argument verification.

Consider the example from your documentation:

    cb.should.have.been.calledWith("hello foo");

That works great for a single, primitive argument, but what about if there are multiple arguments, and some of them you want to do an `eql` comparison on, not an `equal` comparison:

    // A) this long line looks ugly
    // B) it won't work because the object and array won't match
    cb.should.have.been.calledWith("hello foo", {bar: 5}, ['baz', 42, 'qux', 'arbitrarily long string']);

Now I can use Sinon to fix that:

    cb.firstCall.args[0].should.equal('hello foo');
    // Because I'm using eql this works
    cb.firstCall.args[1].should.eql({bar: 5});
    cb.firstCall.args[2].should.eql(['baz', 42, 'qux', 'arbitrarily long string']);

But what would be really nice is if I could use sinon-chai instead, with something like:

    cb.firstCall.shouldHaveArg(0).equal("hello foo");
    cb.firstCall.shouldHaveArg(1).eql({bar: 5});
    cb.firstCall.shouldHaveArg(1).eql(['baz', 42, 'qux', 'arbitrarily long string']);

Have you ever considered adding such functionality?

**Comment by domenic** [comment]
I don't understand why you think the bottom is an improvement over the top? I think it's even more characters...

**Comment by machineghost** [comment]
Touche.  I was more focused on functionality, but I agree the syntax is weaker.  Let me see if I can come up with a cleaner syntax (and if not I'll close the ticket).

**Comment by machineghost** [comment]
In retrospect I think the idea was half-baked; I'll close the ticket until I can think up a clearer value proposition (if I can).
