### ISSUE TITLE
deep.calledWith 

### ISSUE THREAD

**Issue by laggingreflex** [domenic/sinon-chai#83]
I'm expecting an object in arguments:
```
fs.should.have.been.deep.calledWithMatch(undefined, {'a': 1})
```
It throws an error
```
expected outputFile to have been called with arguments matching undefined, { a: 1 }
    outputFile(undefined, {
  "a": 1
}) => [Promise] {  } at Config.<anonymous> ...
```

It seems `deep` doesn't work with `calledWith`, is that correct? If so please consider this as a feature request.

**Comment by domenic** [comment]
Deep is indeed not intended to work with sinon-chai. How would you write the assertion you want using Sinon alone?

**Comment by laggingreflex** [comment]
I would write it as:
```
spy.args[0][0].should.deep.equal({a:1})
```
which I thought might looked better as:
```
spy.should.have.been.deep.calledWith({a:1})
```

**Comment by laggingreflex** [comment]
Actually it seems it does work, even without `deep`:
```
spy({a: {a:1}})
spy.should.have.been.calledWith({a: {a:1}})
```
I was doing something wrong in my original tests, expecting a JSON.stringified object instead of a parsed one, but it does work on deep objects, even without `deep`
