### ISSUE TITLE
ES6 module compatible export

### ISSUE THREAD

**Issue by bradleyayers** [domenic/sinon-chai#85]
At the moment sinon-chai doesn't use an ES6 compatible export. This means that it's impossible to import the library using ES6 *without* the use of an implicit interop translation layer like webpack.

This poses a problem when compiling statically using something like TypeScript, because

```
import sinonChai from 'sinon-chai'
```

will be compiled to ES5 similar to

```
var sinonChai = require('sinonChai').default;
```

Currently there is no default export from the library, so this will fail.

Would you be open to exposing an ES6 export rather than a commonjs style?

**Comment by domenic** [comment]
No; I don't plan to support the fake ES6 that various tools are using (where they use the syntax but don't ues ES6 semantics). I'll wait until we have actual ES6 module support shipping in various browsers and engines.

**Comment by bradleyayers** [comment]
No worries, thanks for the quick response.

**Comment by rfgamaral** [comment]
I was having this issue too and found a workaround if you're using Webpack:

```js
{
    test: require.resolve('sinon-chai'),
    use: [
        {
            loader: 'imports-loader',
            options: {
                require: '>function(){}'
            }
        }
    ]
}
```

**Comment by Fuzzyma** [comment]
Sooo - its 2020. How do I use this package with es6 imports?
