### ISSUE TITLE
lastCalledWith

### ISSUE THREAD

**Issue by appsforartists** [domenic/sinon-chai#87]
It would be nice to be able to assert the value of the most recent call, in idiomatic chai.  How do you feel about:

```javascript
expect(listener).to.have.been.lastCalledWith(value);
// equivalent to
expect(listener.lastCall).to.have.been.calledWith(value);
```

**Comment by domenic** [comment]
In general Sinon-Chai does not add asserters that do not correspond to Sinon.JS assertions. So this needs to be requested on the Sinon.JS repository first.
