### ISSUE TITLE
TypeError: myfunc.should.have.been.called is not a function

### ISSUE THREAD

**Issue by ilogue** [domenic/sinon-chai#88]
This doesn't seem to be allowed:
```
myfunc.draw.should.have.been.called();
```

Although plain chai seems to [support it](http://chaijs.com/plugins/chai-spies/). The downside of this:
```
myfunc.draw.should.have.been.called;
```

is that JSHint doesn't like it.. am I missing something?

**Comment by mlazowik** [comment]
Could be an error in docs: https://github.com/chaijs/chai/issues/371#issuecomment-75034361

**Comment by ilogue** [comment]
Got it! Thanks
