### ISSUE TITLE
[feature request] Add method 'calledOnceWith'

### ISSUE THREAD

**Issue by eGavr** [domenic/sinon-chai#95]
Hi!

I often use these asserts:

```js
assert.calledOnce(spy);
assert.calledWith(spy, 'trololo');
```

It would be great to have an alias:

```js
assert.calledOnceWith(spy, 'trololo');
```

Thank you.

**Comment by domenic** [comment]
We only support methods that are supported by Sinon, so if this is a desired feature, please make a feature request against SinonJS.
