### ISSUE TITLE
Support for Chai 4.0

### ISSUE THREAD

**Issue by layershifter** [domenic/sinon-chai#97]
`chai@4.0.0` was released recently, it will be awesome to get support of it :smile:

**Comment by jraller** [comment]
None of the tests fail when the devDependencies are updated to chai "^4.0.0" and the peerDependencies are changed to ">=1.9.2" for chai. I'm seeing 137 tests passing after making those changes. I have not yet completed reading the breaking changes list at https://github.com/chaijs/chai/releases/tag/4.0.0 so I don't know if additional tests are needed yet.

**Comment by domenic** [comment]
Pull request welcome!

**Comment by Shockolate** [comment]
When support is merged, please update the peer dependency

**Comment by domenic** [comment]
Fixed by https://github.com/domenic/sinon-chai/commit/40b35f3b60aac5757e231a65f88fa0d8352d2903
